### ISSUE TITLE
CUDA backend shouldn't require MPI header file

### ISSUE THREAD

**Issue by luszczek** [icl-utk-edu/heffte#3]
CUDA backend source files `src/heffte_backend_cuda.cu` requires MPI header because of the heFFTe header file it uses:
```C
#include "heffte_backend_cuda.h"
```
This leads to the following chain of headers being included: `heffte_backend_cuda.h` -> `heffte_r2r_executor.h` -> `heffte_pack3d.h` -> `heffte_common.h` -> `heffte_geometry.h` -> `heffte_utils.h` -> `mpi.h`

This requires CUDA compiler to have access to MPI headers but heFFTe's CUDA backend code does not have any calls to MPI.

**Comment by mkstoyanov** [comment]
MPI calls can be use in all sections of the code when testing and debugging.

I don't understand why this is an issue.

**Comment by luszczek** [comment]
This is related to two compilers heFFTe uses : `nvcc` and `mpicc`. The former understands CUDA code but may not know where to find MPI headers. The latter has knowledge of MPI headers and libraries but doesn't understand CUDA code. In order to compile `src/heffte_backend_cuda.cu`, I have to supply path to MPI header file because of the chain of `include` commands listed above. Finding the path to MPI headers depends on the MPI implementation. For example, HPE/Cray CCE doesn't require special flags because it provides the appropriate compiler flags behind the scenes and heFFTe's CUDA backend has issues with a missing header `mpi.h` when using NVCC. And CMake cannot obtain the flags from HPE/Cray CCE because they are implicit. And `nvcc` ends up missing the appropriate path to `mpi.h`.

**Comment by mkstoyanov** [comment]
MPI is a library and not a language extension, so the use of `mpicc` is a bad practice. Linking to a library should be done with -I and -L directives and not with the use of a special wrapper.

In CMake, you should provide `CMAKE_CXX_COMPILER` as `g++` or `clang++`, then specify `CMAKE_CUDA_COMPILER` as nvcc. MPI is specified with `MPI_CXX_COMPILER` or `MPI_HOME` where the first points to `mpicxx` and the second to the install prefix, e.g., `/opt/openmpi_cuda_aware/`. However, the wrapper `mpicxx` will never be used directly, CMake will only read the include paths and library paths from the wrapper and then pass those into the calls to both `g++` and `nvcc`.

If the correct modules are loaded on a system, this should be more or less an automatic process. Can you point me to the system with a problem and can you post the CMake command that produces the issue, the output of the command and the output of `make VERBOSE=1` so we can see how nvcc is getting invoked.

**Comment by mkstoyanov** [comment]
I should elaborate a bit on CMake and compilers in response to both this and a discussion that I've had with @stomov over email.

Once upon a time, the most complex dependence of a math library was MPI and since most people were using non-build systems like Makefiles and even bash scripts, the shortcut was to make wrappers like `mpicc` that would do the proper linking and can accept other flags and simpler dependencies.

However, later we got GPUs and CUDA and we could no longer rely on a single simple wrapper. CUDA is a language extension and `nvcc` was required to compile CUDA code, but `nvcc` didn't have the MPI flags for people the rely on non-build systems, so those people have to do unnecessary and restrictive juggling of code, i.e., avoid `mpi.h` in a file that can contain CUDA kernels. Avoiding such "conflicts" in a large scale project is a waste of time and resources. The problem was further magnified when `nvcc` was not happy about all C++ features and further refactoring and restrictions were imposed, and even more conflicts were caused in transitive dependencies.

The proper solution is to use a build system, such as CMake. The CMake approach is to treat CUDA as a separate language and treat libraries as libraries. Thus, the use of MPI wrappers is avoided, the MPI compile flags can be deduced at configuration time and added to all compilers. CUDA is handled by flagging files that contain CUDA code as build with the CUDA language. Thus:
* MPI flags (i.e., include folders) are added to all compilers
* the CUDA compiler compiles only the CUDA files
* the regular C++ compiler (gcc or clang) is used for the rest of the files
* CUDA specific flags are added only to the CUDA files
* C++ specific flags are added only to the C++ files, and CUDA flags to CUDA, avoiding conflicts between flags
* common flags that can be compiler specific are handled with other variables
    * `-O3` and `-DNDEBUG` are added with `CMAKE_BULD_TYPE=` and expressive values such as Debug, Release, RelWithDebInfo
    * CUDA architectures are specified with `CMAKE_CUDA_ARCHITECTURES`

CMake is a proper build system and gives a lot of features for very little effort, but as we all know it has it's quirks. One of the main CMake problems is that they take a while to add new features and often times will release half-baked features, meaning things that almost work but were not entirely thought through.

CUDA as a hack around wrappers was added in CMake 3.0 and proper CUDA as a language didn't happen until CMake 3.7. Even then, CMake would work with CUDA kernels but would have no native way to handle the math libraries (cuFFT or cuBLAS), the fix didn't happen until 3.17. Many codes are still using the old 3.0 way because of this delay or have to use a bad mix of old ways and CUDA language. heFFTe was using the old way until few months ago, when it turned out that some new machines have a non-standard CUDA installation and the update was absolutely necessary to keep working.

HIP is an even newer concept and HIP as a language didn't happen until CMake 3.21. ROCm libraries have their own CMake files, which is great, but prior to 3.21 the language had to be handled with wrappers once more. Thus, the old way was to use `hipcc` and the CXX flags to manually pass in architecture flags. That means that the flags were given to files that contained no HIP code at all, but all files were parsed looking for such code. Treating CUDA and HIP as separate languages speeds compilation on top of avoiding conflicts. Right now, heFFTe requires CMake 3.19 for CUDA or CPU builds, but CMake 3.21 for HIP. And yes, HIP is still not fully functional in CMake. For example, CUDA has the environment variable "CUDAARCHS" which can be set from administrators on the clusters and all packages will automatically pickup the correct architecture to use. However, there is no such variable for HIP and the architecture still needs to be passed in automatically using `CMAKE_HIP_ARCHITECTURES`.

The best we can all do as a community is to stop using non-build systems of static Makefiles that have to adjusted on every system and stop bending code backwards just to avoid silly things like the `mpi.h` header in CUDA files. We can accept the much better was of CMake and put pressure on CMake developers, system administrators, and vendors, so that we have fast and better resolution to common CMake problems. Everyone needs to have CUDA/HIP architectures specified and that should not have to involve project specific or even system specific work on the side of the user.
